name: pmd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '45 15 * * 2,4,6'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      
      - name: Run PMD
        uses: pmd/pmd-github-action@v2.3.0
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
          version: '6.36.0'
          createGitHubAnnotations: true
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
